import GiftIdeasSection from '@/components/GiftIdeasSection'
import HeroSection from '@/components/HeroSection'
import UpCommingSection from '@/components/UpcommingSection'
import { Metadata } from 'next'
import Image from 'next/image'
import GiftIdeasProductSection from "@/components/GiftIdeasProductSection";

export const metadata: Metadata = {
  title: 'Present till; Present till',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main>
      <HeroSection />
      <GiftIdeasSection />
        <div className="py-[100px]  px-[100px] flex justify-center items-center">
            <div className="w-[40%] flex justify-end pr-20">
                <Image className="object-cover" src="/target.png" width="250" height="250" alt="mission"/>
            </div>
            <div className="w-[60%]">
                <h3 className="text-[32px] font-bold text-primary_color">Our Mission</h3>
                <h4 className="text-[24px] font-semibold text-primary_color pt-[15px]">Our goal to be able to present around <span className="text-secondary_color">1000 gift tips!</span></h4>
                <p className="text-[16px] font-normal pt-[10px]">New stores and collaborations are coming in continuously. The focus is on gifts for special occasions, but among our gift tips you should also be able to find different and odd gift suggestions. We are not afraid to take turns when it comes to gifts of all kinds.</p>
            </div>
        </div>
        <GiftIdeasProductSection />

    </main>
  )
}
