import GiftIdeasSection from '@/components/GiftIdeasSection'
import HeroSection from '@/components/HeroSection'
import UpCommingSection from '@/components/UpcommingSection'
import { Metadata } from 'next'
import Image from 'next/image'
import GiftIdeasProductSection from "@/components/GiftIdeasProductSection";
import Link from "next/link";
import { IoChevronDownOutline } from "react-icons/io5";
import HomeTextSection from "@/components/HomeTextSection";


export const metadata: Metadata = {
  title: 'Present till; Present till',
  description: 'Generated by create next app',
    alternates: {
        canonical: `/`,
        languages: {
            'en-US': '/en-US',
        },
    },
    openGraph: {
        images: '',
    },
}

export default function Home() {
  return (
    <main>
      <HeroSection />
      <GiftIdeasSection />
        <div className=" py-[40px] md:py-[60px] lg:py-[100px] px-5 md:px-[40px] lg:px-[60px] xl:px-[100px] md:flex justify-center items-center">
            <div className=" w-full md:w-[40%] flex justify-center md:justify-end pr-0 md:pr-20">
                <Image className="object-cover" src="/target.png" width="250" height="250" alt="mission"/>
            </div>
            <div className="w-full md:w-[60%] pt-[30px]">
                <h3 className="text-[24px] md:text-[32px] font-bold text-primary_color">Our Mission</h3>
                <h4 className="text-[18px] md:text-[24px] font-semibold text-primary_color pt-[15px]">Our goal to be able to present around <span className="text-heading_2nd_color">1000 gift tips!</span></h4>
                <p className="text-[16px] font-normal pt-[10px]">New stores and collaborations are coming in continuously. The focus is on gifts for special occasions, but among our gift tips you should also be able to find different and odd gift suggestions. We are not afraid to take turns when it comes to gifts of all kinds.</p>
            </div>
        </div>
        <GiftIdeasProductSection />
        <HomeTextSection />
    </main>
  )
}
