import {Metadata} from "next";


export const metadata: Metadata = {
    title: 'Valgorenhet - Present till',
    description: 'Generated by create next app',
    alternates: {
        canonical: `/`,
    },
    openGraph: {
        images: '',
    },
}
export default function Valgorenhet(){
    return(
        <main>

        </main>
    )
}